#' Draw individual(s) from a metacommunity into local community
#'
#' @description
#' Provided a metacommunity object (structured as generated by \code{init_meta()} function),
#' returns a tibble with the number of rows representing recruited individuals.
#' Rows in the output tibble represent indiviuals recruited from the metacommunity (nrows equal to \code{nind}).
#' Columns represent the species ID (arbitrary identifier), the trait value, age of the individual, its body mass, maximum lifespan, and reproductive body mass.
#'
#' Unlike \code{recruit()}, this function will generate a tibble in a format almost ready to \code{bind_rows} with a tibble representing the local community.
#'
#'
#' @param metacom A tibble (dataframe) representing the \strong{metacommunity} with the following columns:
#' \code{species} - species ID, in ascending order relative to the trait value,
#' \code{trait} - species mean trait value,
#' \code{abundance} - expected species abundance,
#' \code{trait_sd} - intraspecific trait variation
#'
#' @param nind A number of individuals to draw, positive integer
#'
#' @param age_crit Numeric; critical age at which half of the individuals die
#'
#' @param mass_crit Numeric; critical mass at which half of the individuals reproduce
#'
#' @returns A tibble (dataframe) representing \code{nind} drawn individuals with the following columns:
#' \code{species} - species ID; \code{trait} - individual trait value; \code{age} - age of the individual; \code{mass} - body mass;
#' \code{lifespan} - maximum lifespan after reaching which the individual will perish;
#' \code{repmass} - body mass after reaching which the individual will asexually reproduce into two children individuals
#'
#' @importFrom stats rexp
#' @importFrom stats runif
#'
#' @export
#'
#' @examples
#' x = init_meta()
#' draw_lcom(x, nind = 1)
#'
#' @seealso \code{init_meta()}, \code{recruit()}
#'
draw_lcom <- function(metacom, nind, age_crit = 10, mass_crit = 5){
  #
  # `metacom` - tibble (dataframe) with the following columns:
  #   `$species` - species ID, in ascending order relative to the trait value
  #   `$trait` - species mean trait value
  #   `$abundance` - expected species abundance
  #   `trait_Sd` - intraspecific trait variation
  # `nind` - number of individuals to draw
  # `age_crit` - critical age at which half of the individuals die
  # `mass_crit` - critical mass at which half of the individuals reproduce
  #
  # Output: tibble (dataframe) with the following columns:
  # `species` - species ID
  # `trait` - individual trait value
  # `age` - age of the individual
  # `mass` - body mass
  # `lifespan` - maximum lifespan
  # `repmass` - mass when reproduction occurs
  #
  if (nind == 0){
    lcom <- tibble(
      species = numeric(0),
      trait = numeric(0),
      age = numeric(0),
      mass = numeric(0),
      lifespan = numeric(0),
      repmass = numeric(0)
    )
  }else{
    lcom <- recruit(metacom = metacom, nind = nind)
    lcom <- lcom %>% mutate(
      age = 1,
      mass = 1,
      #note: runif is truncated to avoid unrealistically high outputs
      # lifespan = pred_logit(p = runif(nind, 0.1, 0.9), crit = age_crit) %>% round(),
      lifespan = rexp(nind, 1/age_crit) %>% round(), # changed death distribution
      repmass = pred_logit(p = runif(nind, 0.1, 0.9), crit = mass_crit)
    )
  }
  return(lcom)
}
