#' Draw a set number of individuals from the metacommunity
#'
#' @description
#' Provided a metacommunity object (structured as generated by \code{init_meta()} function),
#' returns a tibble with the number of rows representing recruited individuals.
#' Rows in the output tibble represent indiviuals recruited from the metacommunity (nrows equal to \code{nind}).
#' Columns represent the species ID (arbitrary identifier), and the trait value.
#' If the species is described as one having no intraspecific trait variation (e.g., \code{trait_sd = 0}),
#' then the trait of a recruited individual will be equal to the species-specific trait value (e.g., \code{trait}), otherwise
#' a small random error will be added drawn from a normal distribution with SD equal to \code{trait_sd}.
#'
#'
#' @param metacom A tibble (dataframe) representing the \strong{metacommunity} with the following columns:
#' \code{species} - species ID, in ascending order relative to the trait value,
#' \code{trait} - species mean trait value,
#' \code{abundance} - expected species abundance,
#' \code{trait_sd} - intraspecific trait variation.
#'
#' @param nind A number of individuals to draw, positive integer.
#'
#' @returns A tibble (dataframe) with the following columns: \code{species} - species ID, \code{trait} - individual trait value.
#' @export
#'
#' @examples
#' x = init_meta()
#' recruit(x)
#'
#' @seealso [init_meta()]
#'
recruit <- function(metacom, nind = 1){
  #
  # `metacom` - tibble (dataframe) with the following columns:
  #   `$species` - species ID, in ascending order relative to the trait value
  #   `$trait` - species mean trait value
  #   `$abundance` - expected species abundance
  #   `$trait_sd` - intraspecific trait variation
  # `nind` - number of individuals to draw
  #
  # Output: tibble (dataframe) with the following columns:
  # `species` - species ID
  # `trait` - individual trait value
  #
  if ((nind %% 1) != 0){
    message("Issue in recruit(): nind is not an integer, returning blank tibble")
    return(tibble(species = numeric(0), trait = numeric(0)))
  }else if (nind == 0){
    return(tibble(species = numeric(0), trait = numeric(0)))
  }else{
    sp_probs <- metacom$abundance / sum(metacom$abundance)
    lucky <- metacom[sample(1:nrow(metacom), size = nind, replace = T, prob = sp_probs), ]
    new_trait <- sapply(1:nrow(lucky), function(i){
      lucky$trait[i] + rnorm(1, 0, lucky$trait_sd[i])
    })
    lucky %>%
      mutate(trait = new_trait) %>%
      select(.data$species, .data$trait)
  }
}
